name: Test

on: push

jobs:
  test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn run lint

      - name: Run unit tests
        run: yarn test

      - name: Run integration tests
        run: yarn run cypress

      - name: Merge code coverage reports
        run: yarn run test:coverage

      - name: Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
